version: '2'
services:
  mysql:
    image: mysql:5.5
    ports:
    - 3306:3306
    container_name: mysql-docker
    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: movieDB
      MYSQL_USER: root
    volumes:
    - /usr/src/home:/var/lib/mysql
  spring:
    image: saishree31/movieapp:1.0
    restart: always
    network_mode: host
    container_name: spring-docker
    depends_on:
    - mysql
    ports:
    - 8080:8080
  mongo:
    image: mongo
    network_mode: host
    container_name: spring-mongo
    ports:
    - 27017:27017
    volumes:
    - /usr/src/home:/data/db